[tool.poetry]
name = "openai-otel"
version = "0.1.0"
description = ""
authors = ["Jingkai He <jingkai@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
